title: The Tech™
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

collections:
  components:
    permalink: /:path
    output: true
  peripherals:
    permalink: /:path
    output: true

just_the_docs:
  collections:
    components:
      name: Components
    peripherals:
      name: Peripherals